mysql:
  dns: root:rootpwd@tcp(127.0.0.1:3306)/mashibing?charset=utf8&parseTime=True&loc=Local
  default_string_size: 256
  disable_datetime_precision: true
  dont_support_rename_index: true
  dont_support_rename_column: true
  skip_initialize_with_version: false