mysql:
  user: root
  password: rootpwd
  ip: 127.0.0.1
  port: 3306
  dataset: mashibing
  charset: utf8
  default_string_size: 256
  disable_datetime_precision: true
  dont_support_rename_index: true
  dont_support_rename_column: true
  skip_initialize_with_version: false