package entity

// User in mysql
// gorm generated by https://www.printlove.cn/tools/sql2gorm (convert mysql table to gorm tag)
// TODO FollowCount, FollowerCount, IsFollow  should be count by other table
type User struct {
	ID              int64  `gorm:"column:id;type:int(11) unsigned;primary_key;AUTO_INCREMENT;comment:用户 ID" json:"id"`      // 用户id
	Name            string `gorm:"column:name;type:varchar(32);unique;comment:用户昵称;NOT NULL" json:"name"`                   // 用户名称
	Password        string `gorm:"column:password;type:varchar(32);comment:用户密码;NOT NULL" json:"password"`                  // 用户密码
	IsFollow        bool   `gorm:"column:is_follow;type:tinyint(1);default:0;comment:true-已关注, false-未关注" json:"is_follow"` // true-已关注，false-未关注
	Avatar          string `gorm:"column:avatar;type:varchar(64);comment:用户头像" json:"avatar"`                               //用户头像
	BackgroundImage string `gorm:"column:background_image;type:varchar(64);comment:用户个人顶部大图" json:"background_image"`       //用户个人页顶部大图
	Signature       string `gorm:"column:signature;type:varchar(64);comment:用户简介" json:"signature"`                         //个人简介
}

func (User) TableName() string {
	return "Users"
}
